src/api/urls.py
from django.urls import path, include
from plugins.api.urls import router as plugins_router

urlpatterns = [
    path("", include(plugins_router.urls)),
]

src/plugins/api/urls.py
from rest_framework import routers

from plugins.api.views import PluginViewSet

router = routers.DefaultRouter()
router.register(r'plugins', PluginViewSet)

src/plugins/urls.py
from django.urls import path

from plugins.views import PluginListView, PluginDetailView, PluginDownloadView

app_name = 'plugins'

urlpatterns = [
    path("", PluginListView.as_view(), name="index"),
    path("download/<str:pk>/", PluginDownloadView.as_view(), name="download"),
    path("<path:tagged_name>/", PluginDetailView.as_view(), name="detail"),

]

src/tf2modportal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from tf2modportal.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path("api/", include("api.urls")),
    path("", index, name="index"),
    path("p/", include("plugins.urls", namespace="plugins")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/plugins/models.py
import re
import uuid
from pathlib import Path

import requests
from django.conf import settings
from django.core.files.storage import default_storage
from django.db import models
from django.utils.text import slugify
from prefix_id import PrefixIDField


class Tag(models.Model):
    id = PrefixIDField(prefix="tag", primary_key=True)
    tagged_name = models.CharField(max_length=255)
    plugin = models.ForeignKey('Plugin', on_delete=models.CASCADE, related_name='tags')
    version = models.CharField(max_length=255)
    is_latest = models.BooleanField(default=False)
    archive_file = models.FileField(upload_to='downloads/plugins', blank=True, null=True)

    def __str__(self):
        return f"{self.tagged_name}"

    def prepare_author(self):
        # Remove spaces from author name, replace with underscores, and make lowercase, e.g. qwizi
        return self.plugin.author.replace(" ", "_").lower()

    def prepare_tagged_name(self):
        # Make the final tagged name, e.g. qwizi/awesomest-plugin:1.0.0 like docker
        author = self.prepare_author()
        return f"{author}/{self.plugin.slug}:{self.version}"

    def save(self, *args, **kwargs):
        if not self.tagged_name:
            self.tagged_name = self.prepare_tagged_name()
        super().save(*args, **kwargs)

    def get_files_structure(self):
        # Get files structure for the plugin, like tree, addons/sourcemod/plugins/plugin_name

        files = self.files.all()
        files_structure = {
            "addons": {
                "sourcemod": {
                    "plugins": [],
                    "scripting": [],
                    "translations": []
                }
            },
        }
        for file in files:
            if file.file_type == PluginFile.FileType.SMX:
                files_structure["addons"]["sourcemod"]["plugins"].append(file.get_file_name())
            if file.file_type == PluginFile.FileType.SP:
                files_structure["addons"]["sourcemod"]["scripting"].append(file.get_file_name())
            if file.file_type == PluginFile.FileType.CFG:
                files_structure["addons"]["sourcemod"]["translations"].append(file.get_file_name())
        return files_structure


class PluginFile(models.Model):
    class FileType(models.TextChoices):
        SMX = 'smx', 'SourceMod Plugin'
        SP = 'sp', 'SourcePawn Script'
        CFG = 'cfg', 'Configuration File'
        ZIP = 'zip', 'Zip Archive'

    id = PrefixIDField(prefix="plugin_file", primary_key=True)
    file_name = models.CharField(max_length=255, default="plugin.smx")
    file_type = models.CharField(max_length=255, choices=FileType.choices, default=FileType.SMX)
    file = models.FileField(upload_to='downloads/plugins/', blank=True, null=True, max_length=255)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE, related_name='files', blank=True, null=True)
    download_url = models.URLField(blank=True, null=True)

    def __str__(self):
        return f"{self.file_type} {self.file.name}"

    def get_file_path(self):
        return Path(settings.MEDIA_ROOT) / self.file.name

    def get_file_name(self):
        return Path(self.file.name).name


class Category(models.Model):
    id = PrefixIDField(prefix="category", primary_key=True)
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class SupportedGame(models.Model):
    id = PrefixIDField(prefix="game", primary_key=True)
    name = models.CharField(max_length=255)
    app_id = models.IntegerField()
    icon = models.URLField()

    def __str__(self):
        return self.name


class Plugin(models.Model):
    class PluginSource(models.TextChoices):
        SOURCEMOD = 'sourcemod', 'SourceMod'
        GITHUB = 'github', 'GitHub'

    id = PrefixIDField(prefix="plugin", primary_key=True)
    short_id = models.CharField(max_length=255, unique=True, blank=True, null=True)
    plugin_source = models.CharField(max_length=50, choices=PluginSource.choices, default=PluginSource.SOURCEMOD)
    supported_games = models.ManyToManyField(SupportedGame, related_name='plugins')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='plugins', blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True, max_length=255)
    name = models.CharField(max_length=255)
    original_name = models.CharField(max_length=255, blank=True, null=True)
    author = models.CharField(max_length=255, blank=True, null=True)
    version = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    url = models.URLField(null=True, blank=True)

    def __str__(self):
        return f"{self.name} - {self.plugin_source}"

    def prepare_name(self):
        # Remove any variations of TF2, Team Fortress 2, version numbers, dates, and special characters
        pattern = re.compile(
            r'\b(TF2|tf2|Team Fortress 2|v?\d+(\.\d+)*|(\d{4}-\d{2}-\d{2})|(\d{2}/\d{2}/\d{4})|[-_:\"\'{}\[\]\\/|.,()])\b',
            re.IGNORECASE)
        cleaned_name = pattern.sub('', self.original_name)
        # Remove any remaining special characters
        cleaned_name = re.sub(r'[-_:\"\'{}\[\]\\/|.,()]', '', cleaned_name)
        # Remove extra spaces
        cleaned_name = re.sub(r'\s+', ' ', cleaned_name)
        return cleaned_name.strip()

    def slugify(self):
        return slugify(self.name)

    def generate_short_id(self):
        while True:
            short_id = str(uuid.uuid4())[:8]
            if not Plugin.objects.filter(short_id=short_id).exists():
                return short_id

    def download_file(self, url, file_name, file_type):
        response = requests.get(url)
        response.raise_for_status()
        file_path = None
        if file_type == PluginFile.FileType.SP:
            file_path = Path(
                settings.MEDIA_ROOT) / "tmp/downloads/plugins/" / self.id / file_name
        if file_type == PluginFile.FileType.SMX:
            file_path = Path(
                settings.MEDIA_ROOT) / "tmp/downloads/plugins/" / self.id / file_name
        file_path.parent.mkdir(parents=True, exist_ok=True)
        with default_storage.open(file_path, 'wb+') as destination:
            destination.write(response.content)

    def get_files_to_download(self, version):
        tag = self.tags.filter(version=version).first()
        if not tag:
            return
        plugin_files = tag.files.filter(download_url__isnull=False).all()
        return plugin_files, tag

    def get_tagged_name(self, version=None):
        if not version:
            return self.tags.first().tagged_name
        return self.tags.filter(version=version).first().tagged_name

    def get_latest_version(self):
        return self.tags.filter(is_latest=True).first().version

    def save(self, *args, **kwargs):
        if not self.short_id:
            self.short_id = self.generate_short_id()
        self.name = self.prepare_name()
        self.slug = self.slugify()
        super().save(*args, **kwargs)

src/plugins/api/views.py
from rest_framework import viewsets, filters

from plugins.api.serializers import PluginSerializer
from plugins.models import Plugin


class PluginViewSet(viewsets.ModelViewSet):
    queryset = Plugin.objects.all()
    serializer_class = PluginSerializer
    filter_backends = [filters.SearchFilter]
    search_fields = ["name", "tags__tagged_name"]

src/plugins/views.py
import os

from django.http import HttpResponse, JsonResponse, FileResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView

from plugins.models import Plugin, Tag


class PluginListView(ListView):
    model = Plugin
    template_name = "plugins/index.html"
    paginate_by = 28
    context_object_name = "plugins"


class PluginDetailView(DetailView):
    model = Plugin
    template_name = 'plugins/detail.html'
    context_object_name = 'plugin'

    def get_object(self):
        tagged_name = self.kwargs['tagged_name']
        return get_object_or_404(Plugin, tags__tagged_name=tagged_name)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag = self.object.tags.get(tagged_name=self.kwargs['tagged_name'])
        files_structure = tag.get_files_structure()
        context['files_structure'] = files_structure
        return context


class PluginDownloadView(View):
    def get(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        tag = get_object_or_404(Tag, pk=pk)
        archive_file = tag.archive_file
        if archive_file:
            file_name = os.path.basename(archive_file.name)
            response = FileResponse(archive_file)
            response['Content-Disposition'] = f'attachment; filename="{file_name}"'
            return response
        return redirect(reverse("plugins:detail", kwargs={"tagged_name": tag.tagged_name}))

src/templates/plugins/detail.html
{% extends "layout/base.html" %}
{% load markdown_extras %}
{% block body %}
    <c-hero title="{{ plugin.name }}">
        {#    <!-- Create card with plugin description -->#}
        {#        <c-card title="Description">#}
        {#            {{ plugin.description }}#}
        {#        </c-card>#}
        {#        <!-- Create card with plugin details -->#}
        {#        <c-card title="Details">#}
        {#            <div class="flex flex-col gap-2">#}
        {#                <c-badge type="neutral">{{ plugin.get_latest_version }}</c-badge>#}
        {#                <span>@{{ plugin.author }}</span>#}
        {#                {{ plugin.get_tagged_name }}#}
        {#            </div>#}
        {#        </c-card>#}
        <!-- Create 2 cards one width 3/4 with description and one with 1/4 with details -->
        <!-- But with the width description 3/4 and details 1/4 -->
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <c-card class="col-span-3" title="Description">
                {{ plugin.description|markdown|safe }}
                <div class="mockup-code">
                    <pre><code>npm i daisyui</code></pre>
                </div>
            </c-card>
            <div class="flex flex-col gap-4 col-span-1">
                <c-card title="Details" h="94">
                    <div class="flex flex-col gap-2">
                        <c-badge type="neutral">{{ plugin.get_latest_version }}</c-badge>
                        <span>@{{ plugin.author }}</span>
                        <c-badge type="primary">{{ plugin.get_tagged_name }}</c-badge>

                        {% for tag in plugin.tags.all %}
                            <details class="collapse bg-base-300">
                                <summary class="collapse-title text-xl font-medium">{{ tag.version }}</summary>
                                <div class="collapse-content">
                                    <p>content</p>
                                </div>
                            </details>
                        {% endfor %}


                    </div>
                </c-card>

                <c-card title="Download" h="full">
                    <ul class="menu bg-base-200 rounded-box w-full">
                        <li>
                            <a href="#" class="menu-title">Folder</a>
                        </li>
                        {% for folder, subfolders in files_structure.items %}
                            <li>
                                <details open>
                                    <summary>{{ folder }}</summary>
                                    <ul>
                                        {% for subfolder, files in subfolders.items %}
                                            <li>
                                                <details open>
                                                    <summary>{{ subfolder }}</summary>
                                                    <ul>
                                                        {% for subsubfolder, subitems in files.items %}
                                                            <li>
                                                                <details open>
                                                                    <summary>{{ subsubfolder }}</summary>
                                                                    <ul>
                                                                        {% for subitem in subitems %}
                                                                            <li><a href="">{{ subitem }}</a></li>
                                                                        {% endfor %}
                                                                    </ul>
                                                                </details>
                                                            </li>
                                                        {% endfor %}
                                                    </ul>
                                                </details>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </details>
                            </li>
                        {% endfor %}
                    </ul>
                    <a href="{% url 'plugins:download' pk=plugin.tags.all.first.pk %}"
                       class="btn btn-primary text-white" hx-boost="false">Download</a>
                    <a href="{{ plugin.url }}"
                       class="btn btn-neutral text-white" target="_blank">Visit
                        plugin page</a>
                </c-card>
            </div>

        </div>
    </c-hero>
{% endblock body %}

src/templates/plugins/index.html
{% extends "layout/base.html" %}

{% block body %}
    <c-hero title="Plugins">
        <c-pagination :page_obj="page_obj"></c-pagination>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            {% for plugin in plugins %}
                <c-card>
                    <div class="flex flex-col gap-2">
                        <h2 class="card-title">
                            <a href="{% url 'plugins:detail' tagged_name=plugin.get_tagged_name %}"
                               hx-boost="true">{{ plugin.name }}</a>
                        </h2>
                        <c-badge type="neutral">{{ plugin.get_latest_version }}</c-badge>
                        <span>@{{ plugin.author }}</span>
                        {{ plugin.get_tagged_name }}
                    </div>
                </c-card>
            {% endfor %}

        </div>
        <c-pagination :page_obj="page_obj"></c-pagination>
    </c-hero>
{% endblock body %}